### ISSUE TITLE
ntopng have a dementia when inside docker container

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ntop/docker-ntop#12]
Well i use ntopng with docker-compose. Because of nature of docker containers every time when you do small change in **docker-compose.yml**. And after running command **docker-compose up -d** ntopng forget all settings which were done in web ui. But i also have to say that default situation even worse i.e all collected data also lost(it is solvable by moving /var/lib/ntopng to separate volume). But gui settings location not documented anywhere so not possible. 
So i have question and suggestion. Please or document where exactly stored settings-> Preferences and settings->Users. Or please make possible to set volume(folder) to store it during runtime. 
It is also will be very nice to have version tags in dockerhub to be able to use previous versions instead of single **latest** tag

**Comment by Raptime** [comment]
I think they use redis to store the config, if you create a volume for /var/lib./redis it should keep the settings.
I wish this would be better documented, it took me a while to figure out.
