### ISSUE TITLE
Can't Build or Setup nscrub

### ISSUE THREAD

**Issue by joonasak** [ntop/docker-ntop#14]
Dear ntop team, I couldn't build nscrub from the dockerfile and I got the error as below:

![image](https://user-images.githubusercontent.com/85352105/210961670-14609781-afe2-4a47-b7f0-9db34c5d0d6d.png)

Please kindly check. Thank you.

**Comment by cardigliano** [comment]
@joonasak it seems you are having some issue accessing the docker registry to download the ubuntu image (this does not depend on our software), the same is working for me

docker build -t nscrub -f Dockerfile.nscrub .
Sending build context to Docker daemon  147.5kB
Step 1/7 : FROM ubuntu:22.04
22.04: Pulling from library/ubuntu
6e3729cf69e0: Pull complete 
Digest: sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132d5a91d098f7f3f9285415a9
Status: Downloaded newer image for ubuntu:22.04
 ---> 6b7dfa7e8fdb
...
