### ISSUE TITLE
NtopNG container restarting:  PF_RING version mismatch

### ISSUE THREAD

**Issue by wahezu** [ntop/docker-ntop#24]
Hi,

I am testing Ntopng using a docker compose file and the stable container from here: https://hub.docker.com/r/ntop/ntopng

As PF_RING package was updated recently to version 8.8.0 on the host and the container has version 8.6.1, I am getting an error and the container restarts constantly:

`[PF_RINGInterface.cpp:67] ERROR: PF_RING version mismatch (expected v.8.6.1 found v.8.8.0)`

I don't find a way to install previous version of PF_RING. 

Can the container stable version in docker hub be updated with PF_RING package v8.8.0??

Thanks

**Comment by cardigliano** [comment]
We are releasing the new stable of ntopng right now, the repository and dockerhub will be updated within tomorrow

**Comment by wahezu** [comment]
Hi @cardigliano ,

I have installed the new container image and now I am getting:

`[PF_RINGInterface.cpp:67] ERROR: PF_RING version mismatch (expected v.8.8.0 found v.8.6.1)`

I have version 8.8.0 installed in the host:

```
server:~/ntopng$ sudo apt list --installed | grep pfring

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

pfring-dkms/unknown,now 8.8.0.9273 all [installed,automatic]
pfring-drivers-zc-dkms/unknown,now 8.8.0-9273 all [installed]
pfring/unknown,now 8.8.0-9273 amd64 [installed]
```

Any hint?

Thanks

**Comment by cardigliano** [comment]
Please check the version reported by /proc/net/pf_ring/info as you probably did not reload the kernel module

**Comment by cardigliano** [comment]
Thank you
